name: auto-release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['16']

    environment:
      name: Production

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '9'

      - name: use node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          registry-url: 'https://registry.npmjs.org'

      - name: install dependencies
        run: pnpm i --frozen-lockfile

      - name: check types
        run: pnpm typecheck

      # - name: lint
      #   run: pnpm lint

      - name: test
        run: pnpm test
        env:
          RECORD_NETWORK_REQUESTS: 'false'
          MOCK_FETCH: 'true'
          CREDENTIAL_ICLOUD_USERNAME: ${{secrets.CREDENTIAL_ICLOUD_USERNAME}}
          CREDENTIAL_ICLOUD_APP_SPECIFIC_PASSWORD: ${{secrets.CREDENTIAL_ICLOUD_APP_SPECIFIC_PASSWORD}}
          CREDENTIAL_GOOGLE_USERNAME: ${{secrets.CREDENTIAL_GOOGLE_USERNAME}}
          CREDENTIAL_GOOGLE_REFRESH_TOKEN: ${{secrets.CREDENTIAL_GOOGLE_REFRESH_TOKEN}}
          CREDENTIAL_GOOGLE_CLIENT_ID: ${{secrets.CREDENTIAL_GOOGLE_CLIENT_ID}}
          CREDENTIAL_GOOGLE_CLIENT_SECRET: ${{secrets.CREDENTIAL_GOOGLE_CLIENT_SECRET}}
          CREDENTIAL_FASTMAIL_USERNAME: ${{secrets.CREDENTIAL_FASTMAIL_USERNAME}}
          CREDENTIAL_FASTMAIL_APP_PASSWORD: ${{secrets.CREDENTIAL_FASTMAIL_APP_PASSWORD}}
          CREDENTIAL_NEXTCLOUD_USERNAME: ${{secrets.CREDENTIAL_NEXTCLOUD_USERNAME}}
          CREDENTIAL_NEXTCLOUD_PASSWORD: ${{secrets.CREDENTIAL_NEXTCLOUD_PASSWORD}}
          CREDENTIAL_NEXTCLOUD_SERVER_URL: ${{secrets.CREDENTIAL_NEXTCLOUD_SERVER_URL}}

      - name: publish package
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
